config/routes.rb
Rackit::Application.routes.draw do
  get "users/index"
  devise_for :users

  resources :products, only: [:index, :show]
  
  get 'popular', to: 'user_product_preferences#index', as: :popular

  resources :users, only: [:index]
  get ':username', to: 'users#show', as: :user

  get ':username/following', to: 'users/followings#index', as: :following
  get ':username/followers', to: 'users/followers#index', as: :followers
  get ':username/feed', to: 'users/feeds#index', as: :feed

  resources :user_product_preferences, only: [:create, :update, :destroy]

  resources :user_friendships, only: [:create, :update, :destroy]

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  has_many :product_preferences, class_name: "UserProductPreference", foreign_key: "user_id"

  has_many :user_friendships
  has_many :friends, through: :user_friendships

  # validates :name, presence: true
  validates :username, presence: true, uniqueness: {case_sensitive: false}, format: /\A[-a-z]+\Z/i

  def racked_products
  	product_preferences.where(is_racked: true)
  end

  # Returns array of users being followed by USER
  def following
    user_friendships
  end

  # Returns array of users following the USER
  def self.followers(user)
    User.joins(:user_friendships).where({ user_friendships: { friend_id: user.id }}).order(:username)
  end

  # Scope method to get all users except the one passed.
  
  def self.all_except(user)
    User.where(arel_table[:id].not_eq(user.id)).order(:name)
  end

  # Overwrites Devise's find_for_database_authentication method in User model.
  # Because we want to change the behavior of the login action, we have to overwrite the find_for_database_authentication method

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

end

app/controllers/users/feeds_controller.rb
class Users::FeedsController < ApplicationController

def index
	@user = User.where(username: params[:username]).first
	# Need to fix this
	@preferences = UserProductPreference.feed(@user)
	@following = @user.following
  @followers = User.followers(@user)
end

end

app/controllers/users/followers_controller.rb
class Users::FollowersController < ApplicationController

def index
	@user = User.where(username: params[:username]).first
	@following = @user.following
  @followers = User.followers(@user)
end

end

app/controllers/users/followings_controller.rb
class Users::FollowingsController < ApplicationController

def index
	@user = User.where(username: params[:username]).first
	@following = @user.following
  @followers = User.followers(@user)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all_except(current_user)
  end

  def show
  	@user = User.where(username: params[:username]).first
  	# @preferences = UserProductPreference.where(user_id: @user.id, is_racked: true).order(created_at: :desc)
  	@preferences = UserProductPreference.rack(@user)
  	@following = @user.following
  	@followers = User.followers(@user)
  end
end

app/helpers/users/feeds_helper.rb
module Users::FeedsHelper
end

app/helpers/users/followers_helper.rb
module Users::FollowersHelper
end

app/helpers/users/followings_helper.rb
module Users::FollowingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_thumbs.html.erb
<% @preferences.each do |p| %>
	<div class="col-md-4 col-xs-12 product_preference_<%=p.id%>">
			<div class="thumbnail">
					<div class ="upp_unrack" data-preference-id="<%= p.id %>">
						<span class="racks"><%= Product.find(p.product_id).racks.count %></span>&nbsp;<span class="glyphicon glyphicon-heart"></span>
					</div>
				<%= image_tag(p.product.product_images.first.image.preview.url, class: "img-responsive") %>
				<div class="caption">
					<%= link_to "View", product_path(p.product_id), class: "btn btn-default btn-sm" %>
					<%= link_to "Buy Now", p.product.buy_url, class: "btn btn-primary btn-sm", target: "_blank" %>
					<h3>
						<%= p.product.name %>
						(<%= number_to_currency(p.product.price / 100) %>)
						<br><small><%= p.product.brand.name %></small>
					</h3>
				</div>
			</div>
	</div>
<% end %>

app/views/users/_useraltnav.html.erb
<div class="user_cloud">
	<h3><%= link_to "@#{@user.username}", user_path(@user.username) %></h3>
	<div class="btn-group btn-group-md follow_links">
		<%= link_to "Following: #{@following.count}", following_path(@user.username), class: "following btn btn-link" %>
		<%= link_to "Followers: #{@followers.count}", followers_path(@user.username), class: "followers btn btn-link" %>
	</div>
</div>

app/views/users/_usernav.html.erb
<div class="user_cloud">
	<h3><%= link_to "@#{@user.username}", user_path(@user.username) %></h3>
	<div class="btn-group btn-group-md follow_links">
		<%= link_to "Following: #{@following.count}", following_path(@user.username), class: "following btn btn-link" %>
		<%= link_to "Followers: #{@followers.count}", followers_path(@user.username), class: "followers btn btn-link" %>
	</div>

	<div class="btn-group btn-group-md">
		<%= link_to user_path(@user.username), class: "my_rack btn" do %>Rack <span class="glyphicon glyphicon-heart"></span><% end %>
		<%= link_to feed_path(@user.username), class: "my_feed btn" do %>Feed <span class="glyphicon glyphicon-user"></span><% end %>
		<%= link_to popular_path, class: "popular btn" do %>Popular <span class="glyphicon glyphicon-fire"></span><% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="friend-follow-div">
  <center><h2>Find Other Rackit Users</h2></center>
    <hr />
      <div id="table">
        <% @users.each do |user| %>
          <div class="trow">
            <span class="tcell">
              <h4><%= link_to "@#{user.username}", user_path(user.username) %>
              <br><small><%= user.created_at.strftime("Member since %m/%d/%Y") %>. <%= user.racked_products.count %><span class="glyphicon glyphicon-heart"></span></small></h4>
            </span>
            <span class="tcell follow-button-width">
              <% if current_user.user_friendships.where(friend_id: user.id).empty? %>
                <div class="follow btn btn-block btn-default" data-friend-id="<%= user.id %>">Follow</div>
              <% else %>
                <div class="unfollow btn btn-block btn-primary" data-friend-id="<%= user.id %>" data-friendship-id="<%= current_user.user_friendships.where(friend_id: user.id).first.id %>">Following</div>
              <% end %>
            </span>
          </div>
        <% end %>
      </div>
</div>

app/views/users/show.html.erb
<div class="col-md-12">
	<%= render "usernav" %>
	<div class="row preferences">
		<%= render "thumbs" %>
	</div>
</div>
<script>
$(document).ready(function() {
  return $('.my_rack').addClass('btn-default active');
});
</script>