config/routes.rb
Rackit::Application.routes.draw do
  get "users/index"
  devise_for :users

  resources :products, only: [:index, :show]
  
  get 'popular', to: 'user_product_preferences#index', as: :popular

  resources :users, only: [:index]
  get ':username', to: 'users#show', as: :user

  get ':username/following', to: 'users/followings#index', as: :following
  get ':username/followers', to: 'users/followers#index', as: :followers
  get ':username/feed', to: 'users/feeds#index', as: :feed

  resources :user_product_preferences, only: [:create, :update, :destroy]

  resources :user_friendships, only: [:create, :update, :destroy]

  root 'home#index'

end

app/views/layouts/_topnav.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		
		<!-- Brand as header -->
		<div class="navbar-header">
			<% if current_user %>
			<%= link_to "Shop Rackit", products_path, class: "navbar-brand" %>
			<% else %>
			<% end %>
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		
		<!-- Collect all other nav links for toggling -->
		<div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
      	<% if current_user %>
      	<!-- Show the full menu with Rack, Find Friends, Logout -->
          <li><%= link_to user_path(current_user.username) do %>
						<span class="glyphicon glyphicon-heart"></span> My Rack
						<% end %>
    			</li>
					<li><%= link_to users_path do %>
						<span class="glyphicon glyphicon-user"></span> Find Friends
						<% end %>
					</li>
					<li><%= link_to edit_user_registration_path do %>
						<span class="glyphicon glyphicon-cog"></span> Settings
						<% end %>
					</li>
					<li class="divider"></li>
					<li><%= link_to destroy_user_session_path, :method => :delete do %>
						<span class="glyphicon glyphicon-log-out"></span> Logout
						<% end %>
					</li>
      	<% else %>
      	<!-- Show just Login -->
	      	<li><%= link_to new_user_session_path do %>
	            	<span class="glyphicon glyphicon-log-in"></span> Login
	            	<% end %></li>
      	<% end %>
      </ul>
    </div>
    <!-- Navbar collapse -->

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Rackit</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta charset="utf-8">
</head>
<body>
<div class="container-fluid">
	<%= render "layouts/topnav" %>
	<%= yield %>
</div>
</body>
</html>